%% Set the criterion functions based on the optCART settings
%
% Currently only a limited set of possibilities is available


function setCritFnc( obj )

if strcmp( obj.type , 'CATE' ) && strcmp( obj.model , 'mean' ) && ...
   strcmp( obj.eval_level , 'leaf-by-leaf' ) && strcmp( obj.criteria , 'athey-imbens' ) && ...
   obj.honest

    obj.crit_split = @treat_mean_lbl_ai_SPLIT_crit;
    obj.crit_ios   = @treat_mean_lbl_ai_crit;
    obj.crit_oos   = @treat_mean_lbl_ai_crit;
    
elseif any( strcmp( obj.type , {'CATE','CLATE' } ) ) && strcmp( obj.model , 'linear' ) && ...
   strcmp( obj.eval_level , 'leaf-by-leaf' ) && strcmp( obj.criteria , 'RDD' ) && ...
   obj.honest

    obj.crit_split = @treat_lin_lbl_RDD_SPLIT_crit;
    obj.crit_ios   = @treat_lin_lbl_RDD_crit;
    obj.crit_oos   = @treat_lin_lbl_RDD_crit;
    
% elseif strcmp( obj.type , 'CATE' ) && strcmp( obj.model , 'linear' ) && ...
%    strcmp( obj.eval_level , 'tree' ) && strcmp( obj.criteria , 'RDD' ) && ...
%    obj.honest
% 
%     obj.crit_split = @treat_lin_tree_RDD_SPLIT_crit;
%     obj.crit_ios   = @treat_lin_tree_RDD_crit;
%     obj.crit_oos   = @treat_lin_tree_RDD_crit;
%     
    
elseif strcmp( obj.type , 'prediction' ) && strcmp( obj.model , 'mean' ) && ...
   strcmp( obj.eval_level , 'leaf-by-leaf' ) && strcmp( obj.criteria , 'MSE' ) && ...
   ~obj.honest

    obj.crit_split = @pred_mean_lbl_MSE_SPLIT_crit;
    obj.crit_ios   = @pred_mean_lbl_MSE_crit;
    obj.crit_oos   = @pred_mean_lbl_MSE_crit;
    
else
    error('optCART:setCritFnc:incorrectType:val',...
          ['Invalid setup for optCART, use one of the following: \n',...
           'type = CATE, honest = true, \n',...
           '    model = mean, criteria = athey-imbens, eval_level = leaf-by-leaf \n',...
           'or \n',...
           '    model = linear, criteria = RDD, \n',...
           '        eval_level = leaf-by-leaf \n',...
           'or \n',...
           'type = CLATE, honest = true, \n',...
           '    model = linear, criteria = RDD, \n',...
           '        eval_level = leaf-by-leaf \n',...
           'type = prediction, honest = false, \n',...
           '    model = mean, criteria = MSE, eval_level = leaf-by-leaf'])
end

end