%% Compute coefficients and M_inverse for split_CT_RDD with Sherman-Morrison formula
%
% Experience: it is faster than lscov if there are more than 10.000 observations or
% less than 3 times the observations


function [ b_y_t_a , b_y_t_b , b_y_c_a , b_y_c_b , ...
           Mi_t_a , Mi_t_b , Mi_c_a , Mi_c_b , ...
           b_w_t_a , b_w_t_b , b_w_c_a , b_w_c_b ] = ...
               sm_est_coeffs( p , n_t , n_c , n_v_t , n_v_c , f_obs_t , l_obs_t , f_obs_c , l_obs_c , ...
                              X0_t , X0_c , Y_t , Y_c , W_t , W_c , fuzzy )
        

%% Compute estimates for valid intent-to-treated group
[ b_y_t_a , b_y_t_b , Mi_t_a , Mi_t_b ,...
  b_w_t_a , b_w_t_b ] = wh_sms_est_coeff( ...
                          p , n_t , n_v_t , f_obs_t , l_obs_t , X0_t , Y_t , W_t , fuzzy );

%% Compute estimates for valid intent-to-control group
[ b_y_c_a , b_y_c_b , Mi_c_a , Mi_c_b ,...
  b_w_c_a , b_w_c_b ] = wh_sms_est_coeff( ...
                          p , n_c , n_v_c , f_obs_c , l_obs_c , X0_c , Y_c , W_c , fuzzy );
                      
end

