%% Heterogeneous treatment effects in Pop-Elches - descriptives
clear all
clc

%% Path
path0 = '/Users/agostonreguly/Documents/Egyetem/CEU/PhD_Topics/project_git/';
%df_all = readtable( horzcat( path0 , 'data/Pop_Elches/dataAER1_R_bw01.csv' ) );
df_all = load( horzcat( path0 , 'data/Pop_Elches/dataAER1_R_bw01.mat' ) );
df_all = df_all.df;
df = df_all( df_all.dzag >= -1.00 & df_all.dzag <= 1.00 & df_all.dzag~=0 , : );
clear df_all

%% Creating descriptives for Heterogeneity check
vNames = {'Peer quality','Taking BA','Grade BA','Scaled Admission score','Num. schools'};
sNames = {'Mean','Median','Std deviation','Min','Max','N'};
cY = [ df.agus , df.bct , df.bcg , df.dzag , df.nusua ];
matrix = [ mean( cY , 'omitnan' ) ; median( cY , 'omitnan') ; ...
            std( cY , 'omitnan') ; min( cY , [], 'omitnan') ; max( cY , [], 'omitnan') ;...
            sum( ~isnan( cY ) ) ];

% Export
matrix2latex(matrix, horzcat(path0,'output/Tables/admin_summary.tex') , ...
    'rowLabels', sNames, 'columnLabels', vNames, ...
    'alignment', 'c', 'format', '%1.2f' );

%% Creating descriptives for discovery
df = readtable( horzcat( path0 , 'data/Pop_Elches/data-AER-7.csv' ) );

vNames = {'Scaled Admission score','School level average transition score', 'No. schools' , '2 schools', '3 schools','4 schools',...
          'Female head of household','Age of head of household','Romanian','Hungarian','Gypsy','Other Ethnicity',...
          'Primary education' ,'Secondary education' , 'Tertiary education' , 'Gender of student'  , 'Age of student',...
          'Parent volunteered' , 'Parent paid tutoring','Parent helps HW','Child does HW every day - Parent',...
          'Negative interactions with peers','Child does HW every day - Child', 'HW percieved easy',...
          'Highest certification proportion - teacher','Proportion of novices',...
          'Car','Internet','Phone','computer',...
          'Mom_educ_primary','Mom_educ_secondary','Mom_educ_tertiary'};
      
[ d_nusua , k_nusua ] = create_dummies( df.nusua );
[ d_tutor , k_tut ] = create_dummies( df.p_tutoring );
ch_rank_peers = str2double( df.ch_rank_peers );%'Rank among peers (1-7)',
exper_rom = str2double( df.experience_Romanian );%'Years of experience'
cY = [ df.dzag , df.agus , df.nusua , d_nusua , ...
       df.head_sex , df.head_age , df.head_nat_romanian , df.head_nat_hungarian , df.head_nat_gypsy , ...
       df.head_nat_other , df.head_educ_primary , df.head_educ_sec , df.head_educ_tertiary , ...
       df.ch_sex , df.ch_age , df.p_d_parent_volunteer , d_tutor( : , 3 ) , df.p_d_homework_help , df.p_d_homework , ...
       df.ch_peers_index_bad , df.ch_d_homework , df.ch_rank_homework_index , ...
       df.didactic_Romanian , df.novice_Romanian , ...
       df.con_car , df.con_internet , df.con_phone , df.con_computer,...
       df.mom_educ_primary,df.mom_educ_secondary,df.mom_educ_tertiary];

matrix2 = [ mean( cY , 'omitnan' ) ; median( cY , 'omitnan') ; ...
            std( cY , 'omitnan') ; min( cY , [], 'omitnan') ; max( cY , [], 'omitnan') ;...
            sum( ~isnan( cY ) ) ];

% Export
matrix2latex(matrix2', horzcat(path0,'output/Tables/survey_summary.tex') , ...
    'rowLabels', vNames, 'columnLabels', sNames, ...
    'alignment', 'c', 'format', '%1.2f' );



